import type { Video } from "@/types/video";

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "GPT-4o Explained: The Future of Multimodal AI",
    description: "A deep dive into OpenAI's latest multimodal model and what it means for AI.",
    aiSummary: "OpenAI's GPT-4o brings together text, vision and audio in one model.",
    videoUrl: "https://www.youtube.com/embed/vgYi3Wr7v_g",
    thumbnailUrl: "https://img.youtube.com/vi/vgYi3Wr7v_g/hqdefault.jpg",
    category: "Model Release",
    topics: ["OpenAI", "GPT-4", "Multimodal"],
    source: "YouTube",
    channel: "OpenAI",
    hours: 5,
    duration: "18:42",
    views: 284000,
    up: 12400,
    down: 180,
    filters: ["trending"],
    score: 95,
  },
  {
    id: "2",
    title: "Intro to Large Language Models",
    description: "A beginner-friendly introduction to how large language models work.",
    aiSummary: "Andrej Karpathy explains LLMs from scratch in simple terms.",
    videoUrl: "https://www.youtube.com/embed/zjkBMFhNj_g",
    thumbnailUrl: "https://img.youtube.com/vi/zjkBMFhNj_g/hqdefault.jpg",
    category: "Tutorial",
    topics: ["LLM", "AI Basics", "Neural Networks"],
    source: "YouTube",
    channel: "Andrej Karpathy",
    hours: 12,
    duration: "59:47",
    views: 1200000,
    up: 58000,
    down: 400,
    filters: ["trending", "tutorial"],
    score: 99,
  },
  {
    id: "3",
    title: "Build a RAG App with LangChain",
    description: "Step-by-step tutorial on building a retrieval augmented generation app.",
    aiSummary: "Learn how to build production RAG apps using LangChain and OpenAI.",
    videoUrl: "https://www.youtube.com/embed/tcqEUSNCn8I",
    thumbnailUrl: "https://img.youtube.com/vi/tcqEUSNCn8I/hqdefault.jpg",
    category: "Tutorial",
    topics: ["LangChain", "RAG", "Python"],
    source: "YouTube",
    channel: "Tech With Tim",
    hours: 24,
    duration: "45:20",
    views: 320000,
    up: 15600,
    down: 290,
    filters: ["tutorial"],
    score: 92,
  },
  {
    id: "4",
    title: "Sam Altman on AGI and the Future of AI",
    description: "Sam Altman talks about OpenAI's mission, AGI timeline and AI safety.",
    aiSummary: "Sam Altman shares his views on AGI arrival and OpenAI's roadmap.",
    videoUrl: "https://www.youtube.com/embed/jvqFAi7vkBc",
    thumbnailUrl: "https://img.youtube.com/vi/jvqFAi7vkBc/hqdefault.jpg",
    category: "Talk",
    topics: ["OpenAI", "AGI", "AI Safety"],
    source: "YouTube",
    channel: "Lex Fridman",
    hours: 72,
    duration: "2:45:00",
    views: 890000,
    up: 42000,
    down: 1200,
    filters: ["talk", "trending"],
    score: 99,
  },
  {
    id: "5",
    title: "Claude 3 vs GPT-4 — Full Comparison",
    description: "Side by side comparison of Anthropic Claude 3 and OpenAI GPT-4.",
    aiSummary: "Detailed benchmark comparison of the two leading AI models.",
    videoUrl: "https://www.youtube.com/embed/T-D1KVIuvjA",
    thumbnailUrl: "https://img.youtube.com/vi/T-D1KVIuvjA/hqdefault.jpg",
    category: "Comparison",
    topics: ["Anthropic", "OpenAI", "Benchmarks"],
    source: "YouTube",
    channel: "AI Explained",
    hours: 12,
    duration: "24:10",
    views: 195000,
    up: 8900,
    down: 210,
    filters: ["trending"],
    score: 88,
  },
  {
    id: "6",
    title: "How to Fine-tune Llama 3",
    description: "Complete guide to fine-tuning Meta's Llama 3 on your own dataset.",
    aiSummary: "Fine-tuning Llama 3 with LoRA and QLoRA for custom use cases.",
    videoUrl: "https://www.youtube.com/embed/Q9zv369Ggfk",
    thumbnailUrl: "https://img.youtube.com/vi/Q9zv369Ggfk/hqdefault.jpg",
    category: "Tutorial",
    topics: ["Meta", "Llama", "Fine-tuning"],
    source: "YouTube",
    channel: "Sentdex",
    hours: 60,
    duration: "51:30",
    views: 210000,
    up: 11000,
    down: 200,
    filters: ["tutorial"],
    score: 89,
  },
  {
    id: "7",
    title: "OpenAI Live Demo — GPT-4 in Action",
    description: "Watch OpenAI demonstrate GPT-4's capabilities live.",
    aiSummary: "Live demo showcasing GPT-4's reasoning and multimodal abilities.",
    videoUrl: "https://www.youtube.com/embed/360ZqfabuPQ",
    thumbnailUrl: "https://img.youtube.com/vi/360ZqfabuPQ/hqdefault.jpg",
    category: "Demo",
    topics: ["OpenAI", "GPT-4", "Demo"],
    source: "YouTube",
    channel: "OpenAI",
    hours: 10,
    duration: "10:00",
    views: 500000,
    up: 25000,
    down: 300,
    filters: ["demo", "trending"],
    score: 97,
  },
  {
    id: "8",
    title: "Google Gemini Live Demo",
    description: "Google demonstrates Gemini's multimodal capabilities live.",
    aiSummary: "Gemini handles text, images and video in real time.",
    videoUrl: "https://www.youtube.com/embed/_fuimO6ErKI",
    thumbnailUrl: "https://img.youtube.com/vi/_fuimO6ErKI/hqdefault.jpg",
    category: "Demo",
    topics: ["Google", "Gemini", "Demo"],
    source: "YouTube",
    channel: "Google",
    hours: 20,
    duration: "8:30",
    views: 620000,
    up: 30000,
    down: 400,
    filters: ["demo", "trending"],
    score: 96,
  },
  {
    id: "9",
    title: "Claude AI Demo — Anthropic",
    description: "Anthropic demonstrates Claude's reasoning and coding abilities.",
    aiSummary: "Claude handles complex reasoning, coding and analysis tasks.",
    videoUrl: "https://www.youtube.com/embed/gZ9IsB72nVk",
    thumbnailUrl: "https://img.youtube.com/vi/gZ9IsB72nVk/hqdefault.jpg",
    category: "Demo",
    topics: ["Anthropic", "Claude", "Demo"],
    source: "YouTube",
    channel: "Anthropic",
    hours: 15,
    duration: "15:20",
    views: 410000,
    up: 19000,
    down: 250,
    filters: ["demo", "trending"],
    score: 94,
  },
  {
    id: "10",
    title: "Meta Ray-Ban AI Glasses — Full Review",
    description: "Testing Meta's Ray-Ban smart glasses with built-in AI assistant.",
    aiSummary: "Meta Ray-Ban glasses bring AI to everyday eyewear.",
    videoUrl: "https://www.youtube.com/embed/e9ZupmL9BcM",
    thumbnailUrl: "https://img.youtube.com/vi/e9ZupmL9BcM/hqdefault.jpg",
    category: "Demo",
    topics: ["Meta", "AI Hardware", "Wearables"],
    source: "YouTube",
    channel: "Anthropic",
    hours: 20,
    duration: "15:20",
    views: 890000,
    up: 32000,
    down: 400,
    filters: ["demo", "trending"],
    score: 91,
  },
  {
    id: "11",
    title: "AI Filmmaking — Create Movies with AI",
    description: "How to use AI tools to create short films and cinematic videos.",
    aiSummary: "AI filmmaking tools are changing how movies are made.",
    videoUrl: "https://www.youtube.com/embed/27i0MleJ6lo",
    thumbnailUrl: "https://img.youtube.com/vi/27i0MleJ6lo/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Video", "Filmmaking", "Creative AI"],
    source: "YouTube",
    channel: "AI Explained",
    hours: 30,
    duration: "28:14",
    views: 540000,
    up: 24000,
    down: 310,
    filters: ["tutorial", "trending"],
    score: 93,
  },
  {
    id: "12",
    title: "AI Image to Video Generation Guide",
    description: "Turn static images into stunning AI-generated videos.",
    aiSummary: "Image to video AI tools are becoming incredibly powerful.",
    videoUrl: "https://www.youtube.com/embed/uW4B6ziQqvY",
    thumbnailUrl: "https://img.youtube.com/vi/uW4B6ziQqvY/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Video", "Image Generation", "Creative AI"],
    source: "YouTube",
    channel: "Yannic Kilcher",
    hours: 40,
    duration: "35:10",
    views: 320000,
    up: 14000,
    down: 200,
    filters: ["tutorial", "trending"],
    score: 90,
  },
  {
    id: "13",
    title: "Google Gemini Omni — Full Introduction",
    description: "Google introduces Gemini Omni with advanced multimodal capabilities.",
    aiSummary: "Gemini Omni brings real-time audio, video and text understanding.",
    videoUrl: "https://www.youtube.com/embed/TglEnUdBb3o",
    thumbnailUrl: "https://img.youtube.com/vi/TglEnUdBb3o/hqdefault.jpg",
    category: "Model Release",
    topics: ["Google", "Gemini", "Multimodal"],
    source: "YouTube",
    channel: "Google",
    hours: 15,
    duration: "12:45",
    views: 670000,
    up: 29000,
    down: 350,
    filters: ["trending"],
    score: 95,
  },
  {
    id: "14",
    title: "What is Nano Banana? AI Explained Simply",
    description: "Breaking down complex AI concepts in simple terms for beginners.",
    aiSummary: "Simple explanations of complex AI topics for everyone.",
    videoUrl: "https://www.youtube.com/embed/zjpi0bR8kNw",
    thumbnailUrl: "https://img.youtube.com/vi/zjpi0bR8kNw/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Basics", "Education", "Beginners"],
    source: "YouTube",
    channel: "Two Minute Papers",
    hours: 25,
    duration: "9:32",
    views: 410000,
    up: 18000,
    down: 220,
    filters: ["tutorial"],
    score: 89,
  },
  {
    id: "15",
    title: "20 Free Unlimited AI Tools You Must Try",
    description: "A complete list of the best free AI tools available in 2024.",
    aiSummary: "These free AI tools can supercharge your productivity.",
    videoUrl: "https://www.youtube.com/embed/ylezKJG7rb8",
    thumbnailUrl: "https://img.youtube.com/vi/ylezKJG7rb8/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Tools", "Free AI", "Productivity"],
    source: "YouTube",
    channel: "Microsoft",
    hours: 35,
    duration: "14:20",
    views: 780000,
    up: 35000,
    down: 500,
    filters: ["tutorial", "trending"],
    score: 94,
  },
  {
    id: "16",
    title: "Bulk Video Automation with AI — Free and Unlimited",
    description: "How to automate bulk video creation using free AI tools.",
    aiSummary: "AI video automation tools can create hundreds of videos automatically.",
    videoUrl: "https://www.youtube.com/embed/lM9Dbf5Qe0Q",
    thumbnailUrl: "https://img.youtube.com/vi/lM9Dbf5Qe0Q/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Automation", "Video AI", "Productivity"],
    source: "YouTube",
    channel: "AI Explained",
    hours: 18,
    duration: "19:45",
    views: 290000,
    up: 13000,
    down: 180,
    filters: ["tutorial", "trending"],
    score: 88,
  },
  {
    id: "17",
    title: "Claude + Seedance 2.0 — AI Video Goldmine",
    description: "Using Claude AI with Seedance 2.0 for powerful AI video creation.",
    aiSummary: "Combining Claude and Seedance creates stunning AI videos.",
    videoUrl: "https://www.youtube.com/embed/SZorAJ4I-sA",
    thumbnailUrl: "https://img.youtube.com/vi/SZorAJ4I-sA/hqdefault.jpg",
    category: "Tutorial",
    topics: ["Claude", "AI Video", "Seedance"],
    source: "YouTube",
    channel: "3Blue1Brown",
    hours: 50,
    duration: "26:32",
    views: 2100000,
    up: 95000,
    down: 800,
    filters: ["tutorial", "trending"],
    score: 99,
  },
  {
    id: "18",
    title: "AI Video Prompt Hacks for Better Results",
    description: "Pro tips and prompt hacks to get better results from AI video tools.",
    aiSummary: "Better prompts lead to dramatically better AI video output.",
    videoUrl: "https://www.youtube.com/embed/n287tR0dHHs",
    thumbnailUrl: "https://img.youtube.com/vi/n287tR0dHHs/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Video", "Prompting", "Tips"],
    source: "YouTube",
    channel: "MKBHD",
    hours: 22,
    duration: "11:18",
    views: 1500000,
    up: 68000,
    down: 900,
    filters: ["tutorial", "trending"],
    score: 96,
  },
  {
    id: "19",
    title: "Get Rich with AI Video Generation in 2024",
    description: "How to make money online using AI video generation tools.",
    aiSummary: "AI video tools are creating new income opportunities online.",
    videoUrl: "https://www.youtube.com/embed/vJifj-JGXCg",
    thumbnailUrl: "https://img.youtube.com/vi/vJifj-JGXCg/hqdefault.jpg",
    category: "Tutorial",
    topics: ["AI Video", "Make Money", "AI Tools"],
    source: "YouTube",
    channel: "Runway",
    hours: 28,
    duration: "8:45",
    views: 380000,
    up: 17000,
    down: 230,
    filters: ["tutorial", "trending"],
    score: 92,
  },
];