import type { Video } from "@/types/video";

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "GPT-4o Explained: The Future of Multimodal AI",
    description: "A deep dive into OpenAI's latest multimodal model and what it means for AI.",
    aiSummary: "OpenAI's GPT-4o brings together text, vision and audio in one model.",
    videoUrl: "https://www.youtube.com/embed/vgYi3Wr7v_g",
    thumbnailUrl: "https://img.youtube.com/vi/vgYi3Wr7v_g/hqdefault.jpg",
    category: "Model Release",
    topics: ["OpenAI", "GPT-4", "Multimodal"],
    source: "YouTube",
    channel: "OpenAI",
    hours: 5,
    duration: "18:42",
    views: 284000,
    up: 12400,
    down: 180,
    filters: ["trending"],
    score: 95,
  },
  {
    id: "2",
    title: "Intro to Large Language Models",
    description: "A beginner-friendly introduction to how large language models work.",
    aiSummary: "Andrej Karpathy explains LLMs from scratch in simple terms.",
    videoUrl: "https://www.youtube.com/embed/zjkBMFhNj_g",
    thumbnailUrl: "https://img.youtube.com/vi/zjkBMFhNj_g/hqdefault.jpg",
    category: "Tutorial",
    topics: ["LLM", "AI Basics", "Neural Networks"],
    source: "YouTube",
    channel: "Andrej Karpathy",
    hours: 12,
    duration: "59:47",
    views: 1200000,
    up: 58000,
    down: 400,
    filters: ["trending", "tutorial"],
    score: 99,
  },
  {
    id: "3",
    title: "Build a RAG App with LangChain",
    description: "Step-by-step tutorial on building a retrieval augmented generation app.",
    aiSummary: "Learn how to build production RAG apps using LangChain and OpenAI.",
    videoUrl: "https://www.youtube.com/embed/tcqEUSNCn8I",
    thumbnailUrl: "https://img.youtube.com/vi/tcqEUSNCn8I/hqdefault.jpg",
    category: "Tutorial",
    topics: ["LangChain", "RAG", "Python"],
    source: "YouTube",
    channel: "Tech With Tim",
    hours: 24,
    duration: "45:20",
    views: 320000,
    up: 15600,
    down: 290,
    filters: ["tutorial"],
    score: 92,
  },
  {
    id: "4",
    title: "Sam Altman on AGI and the Future of AI",
    description: "Sam Altman talks about OpenAI's mission, AGI timeline and AI safety.",
    aiSummary: "Sam Altman shares his views on AGI arrival and OpenAI's roadmap.",
    videoUrl: "https://www.youtube.com/embed/jvqFAi7vkBc",
    thumbnailUrl: "https://img.youtube.com/vi/jvqFAi7vkBc/hqdefault.jpg",
    category: "Talk",
    topics: ["OpenAI", "AGI", "AI Safety"],
    source: "YouTube",
    channel: "Lex Fridman",
    hours: 72,
    duration: "2:45:00",
    views: 890000,
    up: 42000,
    down: 1200,
    filters: ["talk", "trending"],
    score: 99,
  },
  {
    id: "5",
    title: "Claude 3 vs GPT-4 — Full Comparison",
    description: "Side by side comparison of Anthropic Claude 3 and OpenAI GPT-4.",
    aiSummary: "Detailed benchmark comparison of the two leading AI models.",
    videoUrl: "https://www.youtube.com/embed/T-D1KVIuvjA",
thumbnailUrl: "https://img.youtube.com/vi/T-D1KVIuvjA/hqdefault.jpg",
    category: "Comparison",
    topics: ["Anthropic", "OpenAI", "Benchmarks"],
    source: "YouTube",
    channel: "AI Explained",
    hours: 12,
    duration: "24:10",
    views: 195000,
    up: 8900,
    down: 210,
    filters: ["trending"],
    score: 88,
  },
  {
    id: "6",
    title: "How to Fine-tune Llama 3",
    description: "Complete guide to fine-tuning Meta's Llama 3 on your own dataset.",
    aiSummary: "Fine-tuning Llama 3 with LoRA and QLoRA for custom use cases.",
    videoUrl: "https://www.youtube.com/embed/Q9zv369Ggfk",
thumbnailUrl: "https://img.youtube.com/vi/Q9zv369Ggfk/hqdefault.jpg",
    category: "Tutorial",
    topics: ["Meta", "Llama", "Fine-tuning"],
    source: "YouTube",
    channel: "Sentdex",
    hours: 60,
    duration: "51:30",
    views: 210000,
    up: 11000,
    down: 200,
    filters: ["tutorial"],
    score: 89,
  },
  {
    id: "7",
    title: "OpenAI Live Demo — GPT-4 in Action",
    description: "Watch OpenAI demonstrate GPT-4's capabilities live.",
    aiSummary: "Live demo showcasing GPT-4's reasoning and multimodal abilities.",
    videoUrl: "https://www.youtube.com/embed/360ZqfabuPQ",
    thumbnailUrl: "https://img.youtube.com/vi/360ZqfabuPQ/hqdefault.jpg",
    category: "Demo",
    topics: ["OpenAI", "GPT-4", "Demo"],
    source: "YouTube",
    channel: "OpenAI",
    hours: 10,
    duration: "10:00",
    views: 500000,
    up: 25000,
    down: 300,
    filters: ["demo", "trending"],
    score: 97,
  },
  {
    id: "8",
    title: "Google Gemini Live Demo",
    description: "Google demonstrates Gemini's multimodal capabilities live.",
    aiSummary: "Gemini handles text, images and video in real time.",
    videoUrl: "https://www.youtube.com/embed/_fuimO6ErKI",
    thumbnailUrl: "https://img.youtube.com/vi/_fuimO6ErKI/hqdefault.jpg",
    category: "Demo",
    topics: ["Google", "Gemini", "Demo"],
    source: "YouTube",
    channel: "Google",
    hours: 20,
    duration: "8:30",
    views: 620000,
    up: 30000,
    down: 400,
    filters: ["demo", "trending"],
    score: 96,
  },
  {
    id: "9",
    title: "Claude AI Demo — Anthropic",
    description: "Anthropic demonstrates Claude's reasoning and coding abilities.",
    aiSummary: "Claude handles complex reasoning, coding and analysis tasks.",
    videoUrl: "https://www.youtube.com/embed/gZ9IsB72nVk",
    thumbnailUrl: "https://img.youtube.com/vi/gZ9IsB72nVk/hqdefault.jpg",
    category: "Demo",
    topics: ["Anthropic", "Claude", "Demo"],
    source: "YouTube",
    channel: "Anthropic",
    hours: 15,
    duration: "15:20",
    views: 410000,
    up: 19000,
    down: 250,
    filters: ["demo", "trending"],
    score: 94,
  },
];